apiVersion: v1
kind: ConfigMap
metadata:
  name: lakevision-backend-config

data:
  PYICEBERG_CATALOG__DEFAULT__URI: ""
  PYICEBERG_CATALOG__DEFAULT__TOKEN: ""
  PYICEBERG_CATALOG__DEFAULT__WAREHOUSE: ""
  PYICEBERG_CATALOG__DEFAULT__S3__ENDPOINT: ""
  GCP_KEYFILE: ""
  PYICEBERG_CATALOG__GCS__PROJECT_ID: ""
  PYICEBERG_CATALOG__GCS__DEFAULT_BUCKET_LOCATION: ""
  AUTHZ_MODULE_NAME: ""
  AUTHZ_CLASS_NAME: ""