apiVersion: v1
kind: ConfigMap
metadata:
  name: lakevision-frontend-config

data:
  PUBLIC_CHAT_ENABLED: "false"
  PUBLIC_CHAT_SERVER: "ws://localhost:8000/ws"
  PUBLIC_AUTH_ENABLED: "false"
  PUBLIC_OPENID_CLIENT_ID: ""
  PUBLIC_OPENID_PROVIDER_URL: ""
  PUBLIC_REDIRECT_URI: ""
  PUBLIC_COMPANY_NAME: "Apache Iceberg"
  PUBLIC_PLATFORM_NAME: "Lakehouse"
  PUBLIC_EXTRA_LINK: ""
  PUBLIC_EXTRA_LINK_TEXT: ""
  PUBLIC_API_SERVER_SERVER_SIDE: "http://lakevision-backend:8000"